variable "access_key" {}
variable "secret_key" {}
variable "region" {}
variable "zones" {}
variable "vpc_cidr_block" {}
variable "public_cidr_blocks" {}
variable "private_cidr_blocks" {}
variable "ssh_key_name" {}
variable "instance_type" {}
variable "ami_id" {}
variable "poc-asg-max" {}
variable "poc-asg-min" {}
